// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYPFhDvYBHzuSm99fWSbUwItRkpMQPvpk',
    appId: '1:385534588128:web:131ddf240c6301fcfd4c85',
    messagingSenderId: '385534588128',
    projectId: 'todo-10336',
    authDomain: 'todo-10336.firebaseapp.com',
    storageBucket: 'todo-10336.appspot.com',
    measurementId: 'G-6E9XCJX887',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmwOIJu4LOr8K1BVLcuHksYKZ_f5WRqgg',
    appId: '1:385534588128:android:f64c3b4495b2e83dfd4c85',
    messagingSenderId: '385534588128',
    projectId: 'todo-10336',
    storageBucket: 'todo-10336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtXhdGQE4gL6ZATbzr6-vIVdXwyT-QHaE',
    appId: '1:385534588128:ios:a6fd1f2ebbe0c45ffd4c85',
    messagingSenderId: '385534588128',
    projectId: 'todo-10336',
    storageBucket: 'todo-10336.appspot.com',
    iosClientId:
        '385534588128-d0pl8k17bq7ptpu6gep409gb90th9ihg.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtXhdGQE4gL6ZATbzr6-vIVdXwyT-QHaE',
    appId: '1:385534588128:ios:a6fd1f2ebbe0c45ffd4c85',
    messagingSenderId: '385534588128',
    projectId: 'todo-10336',
    storageBucket: 'todo-10336.appspot.com',
    iosClientId:
        '385534588128-d0pl8k17bq7ptpu6gep409gb90th9ihg.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );
}
